# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CrossProdV <- function(X, V, p, q, inverse = FALSE) {
    .Call('mniw_CrossProdV', PACKAGE = 'mniw', X, V, p, q, inverse)
}

LogDensityMultivariateNormal <- function(X, Mu, V) {
    .Call('mniw_LogDensityMultivariateNormal', PACKAGE = 'mniw', X, Mu, V)
}

LogDensityMatrixNormal <- function(X, Mu, RowV, ColV) {
    .Call('mniw_LogDensityMatrixNormal', PACKAGE = 'mniw', X, Mu, RowV, ColV)
}

GenerateMultivariateNormal <- function(N, Lambda, Sigma) {
    .Call('mniw_GenerateMultivariateNormal', PACKAGE = 'mniw', N, Lambda, Sigma)
}

GenerateMatrixNormal <- function(N, Lambda, RowSigma, ColSigma) {
    .Call('mniw_GenerateMatrixNormal', PACKAGE = 'mniw', N, Lambda, RowSigma, ColSigma)
}

GenerateMatrixNIW <- function(N, Lambda, Sigma, Psi, nu, inverse = FALSE) {
    .Call('mniw_GenerateMatrixNIW', PACKAGE = 'mniw', N, Lambda, Sigma, Psi, nu, inverse)
}

GenerateRandomEffectsNormal <- function(N, lambda, y, V, A) {
    .Call('mniw_GenerateRandomEffectsNormal', PACKAGE = 'mniw', N, lambda, y, V, A)
}

HierUneqVModelGibbs <- function(nSamples, nBurn, Y, X, V, Lambda, Omega, Psi, nu, updateBetaSigma = TRUE, updateMu = TRUE, storeBetaSigma = TRUE, storeMu = TRUE) {
    .Call('mniw_HierUneqVModelGibbs', PACKAGE = 'mniw', nSamples, nBurn, Y, X, V, Lambda, Omega, Psi, nu, updateBetaSigma, updateMu, storeBetaSigma, storeMu)
}

LogDensityWishart <- function(X, Psi, nu, inverse = FALSE) {
    .Call('mniw_LogDensityWishart', PACKAGE = 'mniw', X, Psi, nu, inverse)
}

GenerateWishart <- function(N, Psi, nu, inverse = FALSE) {
    .Call('mniw_GenerateWishart', PACKAGE = 'mniw', N, Psi, nu, inverse)
}

